version: "3.8"

# Note:
# - Uncomment the volumes and volumes in the backend and frontend services for hot reloading

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database_net

  backend:
    build:
      context: ./backend/
      dockerfile: ./dockerfiles/${NODE_ENV}.Dockerfile
      args:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEST_PORT=${NEST_PORT}
      - FRONTEND=${FRONTEND}
      - JWT_SECRET=${JWT_SECRET}
      - FT_CLIENT_ID=${FT_CLIENT_ID}
      - FT_CLIENT_SECRET=${FT_CLIENT_SECRET}
      - FT_REDIRECT_URI=${FT_REDIRECT_URI}
      - FT_PROFILE_URL=${FT_PROFILE_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_VERIFY_SERVICE_SID=${TWILIO_VERIFY_SERVICE_SID}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${NEST_PORT:-3000}:${NEST_PORT:-3000}"
      - "5555:5555"
    networks:
      - database_net
      - frontend_net
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./dockerfiles/${NODE_ENV}.Dockerfile
      args:
        - BACKEND=${BACKEND}
        - PORT=${NEXT_PORT}
        - BACKEND_SERVICE=backend:$NEST_PORT
        - JWT_SECRET=${JWT_SECRET}
    container_name: frontend
    restart: always
    ports:
      - "${NEXT_PORT:-3001}:${NEXT_PORT:-3001}"
    environment:
      - NEXT_PORT=${NEXT_PORT}
      - BACKEND=${BACKEND}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - backend
    networks:
      - frontend_net
    volumes:
      - ./frontend:/app

volumes:
  db-data:

networks:
  database_net:
    driver: bridge
  frontend_net:
    driver: bridge