version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local_net

  backend:
    build:
      context: requirements/backend/
      dockerfile: Dockerfile # dockerfiles/${NODE_ENV}.Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - "${NESTJS_PORT:-3000}:${NESTJS_PORT:-3000}"
      - "5555:5555"
    volumes:
      - ./requirements/backend:/app # for hot reloading
      # - node_modules:/app/node_modules # for faster builds
    networks:
      - local_net
    depends_on:
      - db
    command:
      - sh
      - -c
      - |
        npm install
        npm run prisma
        npm run start:dev

  frontend:
    build:
      context: requirements/frontend/
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "${NEXTJS_PORT:-3001}:${NEXTJS_PORT:-3001}"
    env_file: .env
    volumes:
      - ./requirements/frontend:/app # for hot reloading
    networks:
      - local_net
    depends_on:
      - backend
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local_net
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:

networks:
  local_net:
    driver: bridge
